{
 "title": "Alarms",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Alarms list",
   "type": "alertlist",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "mysql_slow_queries per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(mysql_slow_queries[5m]) ", "legendFormat": " " }
   ]
  },
  {
   "title": "query_response_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_exporter_collector_duration_seconds{app=\"mariadb\",collector=\"collect.info_schema.query_response_time\",release=\"payeverdb\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Free space per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "Gib" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes/(1024*1024*1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU per pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{job=\"kubernetes-nodes-cadvisor\",namespace=\"default\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}