# config file version
apiVersion: 1

# list of datasources to insert/update depending
# on what's available in the database
datasources:
  - name: MySQL
    type: mysql
    typeLogoUrl: public/app/plugins/datasource/mysql/img/mysql_logo.svg
    access: proxy
    url: payeverdb-mariadb:3306
    password: ""
    user: payeverdb
    database: payeverdb
    basicAuth: false
    isDefault: false
    jsonData: {}
    readOnly: false

  - name: Prometheus
    type: prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://prometheus-server
    # password:
    # user: ""
    # database:
    basicAuth: false
    isDefault: true
    jsonData: {}
    readOnly: false
