---
replication.enabled: "false"
# master.livenessProbe.enabled: false
# master.readinessProbe.enabled: false
# slave.livenessProbe.enabled: false
# slave.readinessProbe.enabled: false
master.persistence.enabled: "true"
# master.persistence.existingClaim: payeverdb-pv-claim
# master.persistence.annotations: {}
initdbScriptsConfigMap: initdb
db:
  name: payeverdb
  user: payeverdb
  password: caf2wodNak
rootUser:
  password: caf2wodNak
  forcePassword: "true"
metrics:
  enabled: true
  ## Extra args to be passed to mysqld_exporter
  ## ref: https://github.com/prometheus/mysqld_exporter/
  ##
  extraArgs:
    master:
    - --collect.global_status
    - --collect.info_schema.clientstats
    - --collect.info_schema.query_response_time
    - --collect.info_schema.userstats
    - --collect.heartbeat

    # slave: []
    # - --collect.auto_increment.columns
    # - --collect.binlog_size
    # - --collect.engine_innodb_status
    # - --collect.engine_tokudb_status
    # - --collect.global_status
    # - --collect.global_variables
    # - --collect.info_schema.clientstats
    # - --collect.info_schema.innodb_metrics
    # - --collect.info_schema.innodb_tablespaces
    # - --collect.info_schema.innodb_cmp
    # - --collect.info_schema.innodb_cmpmem
    # - --collect.info_schema.processlist
    # - --collect.info_schema.processlist.min_time
    # - --collect.info_schema.query_response_time
    # - --collect.info_schema.tables
    # - --collect.info_schema.tables.databases
    # - --collect.info_schema.tablestats
    # - --collect.info_schema.userstats
    # - --collect.perf_schema.eventsstatements
    # - --collect.perf_schema.eventsstatements.digest_text_limit
    # - --collect.perf_schema.eventsstatements.limit
    # - --collect.perf_schema.eventsstatements.timelimit
    # - --collect.perf_schema.eventswaits
    # - --collect.perf_schema.file_events
    # - --collect.perf_schema.file_instances
    # - --collect.perf_schema.indexiowaits
    # - --collect.perf_schema.tableiowaits
    # - --collect.perf_schema.tablelocks
    # - --collect.perf_schema.replication_group_member_stats
    # - --collect.slave_status
    # - --collect.slave_hosts
    # - --collect.heartbeat
    # - --collect.heartbeat.database
    # - --collect.heartbeat.table
master:
  ## Configure MySQL with a custom my.cnf file
  ## ref: https://mysql.com/kb/en/mysql/configuring-mysql-with-mycnf/#example-of-configuration-file
  ##
  config: |-
    [mysqld]
    slow_query_log=1
    long_query_time=0.1
    log_queries_not_using_indexes=1
    log_output = TABLE;
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    plugin_dir=/opt/bitnami/mariadb/plugin
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mariadb/plugin
    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

slave:
  ## Configure MySQL slave with a custom my.cnf file
  ## ref: https://mysql.com/kb/en/mysql/configuring-mysql-with-mycnf/#example-of-configuration-file
  ##
  config: |-
    [mysqld]
    slow_query_log=1
    long_query_time=0.1
    log_queries_not_using_indexes=1
    log_output = TABLE;
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8
    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid